### ISSUE TITLE
Adding 3rd party helpers

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport-handlebars#2]
There is a number of libraries that expose some really useful handlebar helpers.
For example:
http://formatjs.io/handlebars/
https://github.com/assemble/handlebars-helpers

Is there a way to add these and expose them for usage in templates that use handlebars engine?
How would one do this?

Thanks
Z.

**Comment by pofider** [comment]
I've add this to docs.... http://jsreport.net/learn/handlebars

There are plenty of thirdparty libraries providing additional handlebars helpers like [handlebars-helpers](https://github.com/assemble/handlebars-helpers) or [handlebars-intl](http://formatjs.io/handlebars/). To use such a library in jsreport, you need to install it from npm and then `require` it at the top of the template's helpers.

`npm install handlebars-intl`

``` js
var handlebars = require('handlebars');

var HandlebarsIntl = require('handlebars-intl');
HandlebarsIntl.registerWith(handlebars);
```

`npm install handlebars-helpers`

``` js
var handlebars = require('handlebars');

var helpers = require('handlebars-helpers')({
  handlebars: handlebars
});
```

**Comment by zam6ak** [comment]
Can this be used in common helpers script that is being used by all reports?
I am referring to this: http://jsreport.net/blog/reusing-template-helpers

**Comment by pofider** [comment]
Yes this should work as well.

Later we implement global scripts so you don't have too attach scripts to the new templates. It will automatically run for all of them. And the puzzle will be complete https://github.com/jsreport/jsreport-scripts/issues/4

**Comment by zam6ak** [comment]
Hmm...
This does not seem to work with phantom-js...
With html template and handlebars I specify the common script, it works...but when I switch to phantom-js , it does not....

error:

```
2016-10-26T19:02:08.743Z - warn: Error when processing render request Error during rendering report: Identifier 'moment' has already been declared evalmachine.<anonymous>:27
    const moment = require('moment-timezone');
                                            ^
SyntaxError: Identifier 'moment' has already been declared
    at Object.exports.runInNewContext (vm.js:71:16)
    at module.exports (X:\Projects\exaweb\jsreport\node_modules\jsreport-core\lib\render\engineScript.js:150:10)
    at IncomingMessage.<anonymous> (X:\Projects\exaweb\jsreport\node_modules\script-manager\lib\worker-servers.js:160:57)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by pofider** [comment]
This is likely crashing because script also runs for headers and footers. Try to put this at the top of the script:

``` js
 if (req.options.isChildRequest)
      return done();
```

**Comment by zam6ak** [comment]
Does that snippet goes inside onBeforeRender() or on top of the script or on top of the script that is being added to helpers?

**Comment by pofider** [comment]
Sorry... to onBeforeRender

**Comment by zam6ak** [comment]
Ok but when the child is using a function from helpers script it errors out now :(

Here is my function:

```
function beforeRender(req, res, done) {
    // prevent 'double include' when rendering child templates 
    if (req.options.isChildRequest) {
        return done();
    }
    //console.log(commonHelpersScript);
    req.template.helpers += commonHelpersScript;
    done();
} 
```

Error I get when rendering PDF:

```
2016-10-27T12:52:51.766Z - warn: Error when processing render request Error during rendering report: Missing helper: "toTimeZone" Error: Missing helper: "toTimeZone"
    at Object.<anonymous> (X:\Projects\MYAPP\jsreport\node_modules\handlebars\dist\cjs\handlebars\helpers\helper-missing.js:19:13)
```

**Comment by zam6ak** [comment]
Please disregard.
It seems like the child template has to reference shared script also (even though, the parent is already mentioning it)

A bit tedious, but it works....Looks like jsreport/jsreport-scripts#4 would be a great resolution....

**Comment by rchancey** [comment]
How can I add the helpers if I am using jsreport core? 

const jsreport = require('jsreport-core')({
        connectionString: { name: 'fs', syncModifications: true }
    }
)
const jsrender = require('jsreport-jsrender')
const handlebars = require('jsreport-handlebars')
const templates = require('jsreport-templates')
const xlsx = require('jsreport-xlsx')
const data = require('jsreport-data')
const scripts = require('jsreport-scripts')
const assets = require('jsreport-assets')
const helpers = require('handlebars-helpers');
const phantomPdf = require('jsreport-phantom-pdf')
const fsStore = require('jsreport-fs-store')
jsreport.use(jsrender())
jsreport.use(handlebars())
jsreport.use(helpers({
    handlebars: handlebars
  }))


I get this error because handlebars from jsreport-handlebars is not the underlying handlebars somehow.

please offer any suggestions.. this has been driving me nuts for a few days :P 

module initialization error: TypeError
at /var/task/node_modules/handlebars-helpers/index.js:36:11
at forIn (/var/task/node_modules/for-in/index.js:12:12)
at helpers (/var/task/node_modules/handlebars-helpers/index.js:35:5)
at Object.<anonymous> (/var/task/lib/reporting.js:52:14)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/index.js:3:18)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
