### ISSUE TITLE
undefined function when reusing helpers

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport-handlebars#3]
Hi

I am trying to follow instructions on [reusing template helpers](http://jsreport.net/blog/reusing-template-helpers) and am running into an issue where my helper function that is using external library is not defined.

Here is my script

```
const moment = require('moment-timezone');
const handlebars = require('handlebars');

// Assemble.io Handlebars helper library - https://github.com/assemble/handlebars-helpers
const assembleIoHelpers = require('handlebars-helpers')({
  handlebars: handlebars
});


function toTimeZone(value, timeZone, format) {
    console.log(value, timeZone, format);
    return moment(value).tz(timeZone).format(format); //  ReferenceError: moment is not defined
}


function beforeRender(req, res, done) {
  console.log('beforeRender');
  console.log(moment().format()); // this works

  // http://jsreport.net/blog/reusing-template-helpers
  req.template.helpers += '\n' + assembleIoHelpers.math
                        + '\n' + toTimeZone;

  done();
}
```

And here is the error I get when running the template that is using the helper

```
2016-10-25T15:50:24.573Z - warn: Error when processing render request Error during rendering report: moment is not defined ReferenceError: moment is not defined
    at Object.toTimeZone (evalmachine.<anonymous>:16:12)
    at Object.eval (eval at createFunctionContext (X:\Projects\MYAPP\jsreport\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:24:78)
    at main (X:\Projects\MYAPP\jsreport\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (X:\Projects\MYAPP\jsreport\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (X:\Projects\MYAPP\jsreport\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at X:\Projects\MYAPP\jsreport\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:26:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)

```

If I use the same function with require directly in the report helper section, it works.
But then it is not reusable...

Thanks
Z!

**Comment by pofider** [comment]
The idea of the trick is that you add the function implementation strings by concatenating the functions. This doesn't add the function reference.

``` js
//declare artificial function which adds helpers from the package
function addHelpers() {
    const handlebars = require('handlebars');

    const assembleIoHelpers = require('handlebars-helpers')({
        handlebars: handlebars
    });
}

//create our own timezone function
function toTimeZone(value, timeZone, format) {
    /*get the moment, or we would need to add this string to the req.template.helpers require(\'moment-timezone\');*/
    const moment = require('moment-timezone');
    console.log(value, timeZone, format);
    return moment(value).tz(timeZone).format(format); 
}


function beforeRender(req, res, done) {
  //add implementation text of artificial function
  //call that function
  //add implementation text of toTimeZone helper
  req.template.helpers += '\n' + addHelpers + '\naddHelpers()' + '\n' + toTimeZone;

  done();
}
```

This looks very weird, but it makes sense because the script and task runs in different sandbox on different process and in jsreportonline also on different servers.

**Comment by zam6ak** [comment]
Wow :) I mean....OK...
So req.templates.helpers is just a string that represents a script to be executed.....

I have reworked your version to be a bit more easier on the eyes....

```
function toTimeZone(value, timeZone, format) {
    console.log(value, timeZone, format);
    return moment(value).tz(timeZone).format(format);
}


// "req.template.helpers" is a string, to which we need to add reusable helpers
// using ES6 template strings we can write all reusable functions as regular JS functions and then include them in the script.
const commonHelpersScript = `
    const moment = require('moment-timezone');
    const handlebars = require('handlebars');

    const assembleIoHelpers = require('handlebars-helpers')({
      handlebars: handlebars
    });

    // --- reusable helpers ---
    ${toTimeZone}
    // --- reusable helpers ---
`;

function beforeRender(req, res, done) {
    console.log('--------------', commonHelpersScript, '-----------------');
    req.template.helpers += commonHelpersScript;
    done();
}    

```

One could put this in a file and just read file contents in beforeRender...
But that would be included every time....

Seems like there should be a way (via config), where you could specify a js file to load reusable helpers from at startup....

**Comment by pofider** [comment]
Yes, this should be also solved with a new static-resources extension... I'm totally overwhelmed, sorry it takes some time.
